<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hfwupersonal"
 *
 * Auto generated by Extension Builder 2014-11-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'HFWU Personal',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Stefan Froemken',
	'author_email' => 'sfroemken@jweiland.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);